Feature/28 site with schedule
compostage-dans-ma-ville/backend pull request #29
Opened 2023-03-07 19:47 UTC by Lyokolux

Built on top of https://github.com/compostage-dans-ma-ville/backend/pull/27

2023-03-08 09:06 UTC, johannchopin requested changes

2023-03-08 09:06 UTC, johannchopin commented on prisma/schema.prisma
> +  close Int
Ça ne peut pas marcher de la sorte => impossible de savoir si un jour est ouvert toute la journée. Et ajouter un boolean `isOpenedAllDay` est un anti-pattern pour moi 🤔

2023-03-24 08:49 UTC, johannchopin requested changes
Vraiment nice 👍 Manque plus que quelque details mais après on aura un magnifique example d'une entity bien géré 🙌

2023-03-24 08:49 UTC, johannchopin commented on src/site/dto/GetSite.dto.ts
> +      description: 'There are 7 cells in the array. One for every day starting on Monday. Null represents a closed day, an empty array a 24-hour opening on this day.',
Parfait 👍

2023-03-24 08:49 UTC, johannchopin commented on src/site/dto/GetSite.dto.ts
> +        $ref: getSchemaPath(GetOpeningDto)
Très pratique ce `getSchemaPath` 👌

2023-03-24 08:49 UTC, johannchopin commented on src/site/site.controller.ts
> +    return formattedSite
Utilise `plainToClass` pour la safety de bien utiliser le dto 😉:

```suggestion
    return plainToClass(
      GetSiteDto,
      formattedSite
    )
```

Un example: https://github.com/compostage-dans-ma-ville/backend/blob/main/src/auth/auth.controller.ts#L46

2023-03-24 08:49 UTC, johannchopin commented on src/site/site.controller.ts
> +    if (!site) return undefined
Ça trigger un 404 de return un `undefined`?

Je recommande d'utiliser la manière nestjs en utilisant les [exceptions](https://docs.nestjs.com/exception-filters):

```
  if (!site) {
    throw new NotFoundException(`Site with id ${siteId} does not exist`);
  }
```

2023-03-24 08:49 UTC, johannchopin commented on src/site/site.service.ts
> +    DailySchedules: Array<DailySchedule & { openings: Opening[] }>;
Pas la peine d'utiliser un type custom. Prisma génère des payloads avec pas mal d'helpers notamment `include`:

```
Prisma.SiteGetPayload<{ include: { DailySchedules: true } }>
```

2023-03-24 21:09 UTC, Lyokolux commented on src/site/site.controller.ts
> +    if (!site) return undefined
Il y a un intercepteur pour cela

2023-03-24 21:10 UTC, Lyokolux commented on src/site/site.controller.ts
> +    if (!site) return undefined
Si le site n'est pas trouvé, prisma renvoie une erreur dans ce cas. Cette erreur est récupéré par le `NotFoundInterceptor`.

2023-03-24 21:29 UTC, Lyokolux commented on src/site/site.service.ts
> +    DailySchedules: Array<DailySchedule & { openings: Opening[] }>;
Ce type alourdi le code plus qu'autre chose:
```ts
Prisma.SiteGetPayload<
      {
        include: {
          Address: true,
          DailySchedules: {
            include: {
              openings: true
            }
          },
          Images: true,
          Organization: true
        }
      }
    >
```

Il retourne d'ailleurs une erreur: 
>... is missing the following properties from type 'Site': id, createdAt, updatedAt, name, and 3 more.

2023-03-24 21:37 UTC, johannchopin commented on src/site/site.service.ts
> +    DailySchedules: Array<DailySchedule & { openings: Opening[] }>;
Tu veux dire ne pas typer le retour de la fonction ? En soit oui vue que les types prisma sont robuste.

2023-03-24 21:46 UTC, johannchopin commented on src/site/site.controller.ts
> +    return formattedSite
@Lyokolux pk il est marqué comme resolved alors que non? 🤔

2023-03-24 21:51 UTC, Lyokolux commented on src/site/site.service.ts
> +    DailySchedules: Array<DailySchedule & { openings: Opening[] }>;
> Tu veux dire ne pas typer le retour de la fonction ? En soit oui vue que les types prisma sont robuste.

Si le type retourné par findOne change, les erreurs en TS seront affichées pour chaque utilisation de la fonction.

2023-03-24 21:55 UTC, johannchopin commented on src/site/site.service.ts
> +    DailySchedules: Array<DailySchedule & { openings: Opening[] }>;
Yes bah oui faisons comme ça 👌 dans les services vu que c'est juste un retour de prisma c'est pas pertinents de forcer le type de retour 👌

2023-03-24 22:06 UTC, Lyokolux commented on src/site/site.controller.ts
> +    return formattedSite
Un git push --force  a supprimé ce commit

2023-03-24 22:14 UTC, johannchopin approved these changes
Youhouuuu 🥰hâte de tester avec le front

2023-03-26 07:46 UTC, merged